CREATE TABLE `account_registration_fact` (
  `date_fk` int(11) DEFAULT NULL,
  `flashnotes_date_fk` int(11) DEFAULT NULL,
  `user_fk` int(11) DEFAULT NULL,
  `school_fk` int(11) DEFAULT NULL,
  `disability_program_fk` int(11) DEFAULT NULL,
  `affiliate_fk` int(11) DEFAULT NULL,
  `site_fk` int(11) DEFAULT NULL,
  `referral_utm_source` varchar(45) DEFAULT NULL,
  `referral_utm_medium` varchar(45) DEFAULT NULL,
  `referral_utm_campaign` varchar(45) DEFAULT NULL,
  `registration_datetime` datetime DEFAULT NULL,
  KEY `account_registration_date_idx` (`date_fk`),
  KEY `account_registration_flashnotes_date_idx` (`flashnotes_date_fk`),
  KEY `account_registration_user_idx` (`user_fk`),
  KEY `account_registration_school_idx` (`school_fk`),
  KEY `account_registration_disability_program_idx` (`disability_program_fk`),
  KEY `account_registration_affiliate_idx` (`affiliate_fk`),
  KEY `account_registration_site_idx` (`site_fk`),
  CONSTRAINT `account_registration_affiliate` FOREIGN KEY (`affiliate_fk`) REFERENCES `affiliate_dim` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `account_registration_date` FOREIGN KEY (`date_fk`) REFERENCES `date_dim` (`date_key`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `account_registration_disability_program` FOREIGN KEY (`disability_program_fk`) REFERENCES `disability_program_dim` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `account_registration_flashnotes_date` FOREIGN KEY (`flashnotes_date_fk`) REFERENCES `date_dim` (`date_key`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `account_registration_school` FOREIGN KEY (`school_fk`) REFERENCES `school_dim` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `account_registration_site` FOREIGN KEY (`site_fk`) REFERENCES `site_dim` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `account_registration_user` FOREIGN KEY (`user_fk`) REFERENCES `user_dim` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8