CREATE TABLE `product_upload_fact` (
  `date_fk` int(11) DEFAULT NULL,
  `flashnotes_date_fk` int(11) DEFAULT NULL,
  `product_fk` int(11) DEFAULT NULL,
  `school_fk` int(11) DEFAULT NULL,
  `course_fk` int(11) DEFAULT NULL,
  `seller_fk` int(11) DEFAULT NULL,
  `seller_disability_program_fk` int(11) DEFAULT NULL,
  `site_fk` int(11) DEFAULT NULL,
  `upload_datetime` datetime DEFAULT NULL,
  `affiliate_fk` int(11) DEFAULT NULL,
  KEY `product_upload_product_fk_idx` (`product_fk`),
  KEY `product_upload_school_fk_idx` (`school_fk`),
  KEY `product_upload_date_idx` (`date_fk`),
  KEY `product_upload_flashnotes_date_idx` (`flashnotes_date_fk`),
  KEY `product_upload_course_idx` (`course_fk`),
  KEY `product_upload_seller_idx` (`seller_fk`),
  KEY `product_upload_seller_disability_program_idx` (`seller_disability_program_fk`),
  KEY `product_upload_site_idx` (`site_fk`),
  KEY `product_upload_affiliate_idx` (`affiliate_fk`),
  CONSTRAINT `product_upload_affiliate` FOREIGN KEY (`affiliate_fk`) REFERENCES `affiliate_dim` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `product_upload_course` FOREIGN KEY (`course_fk`) REFERENCES `course_dim` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `product_upload_date` FOREIGN KEY (`date_fk`) REFERENCES `date_dim` (`date_key`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `product_upload_flashnotes_date` FOREIGN KEY (`flashnotes_date_fk`) REFERENCES `date_dim` (`date_key`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `product_upload_product` FOREIGN KEY (`product_fk`) REFERENCES `product_dim` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `product_upload_school` FOREIGN KEY (`school_fk`) REFERENCES `school_dim` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `product_upload_seller` FOREIGN KEY (`seller_fk`) REFERENCES `user_dim` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `product_upload_seller_disability_program` FOREIGN KEY (`seller_disability_program_fk`) REFERENCES `disability_program_dim` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `product_upload_site` FOREIGN KEY (`site_fk`) REFERENCES `site_dim` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8
