CREATE TABLE `product_sale_fact` (
  `date_fk` int(11) DEFAULT NULL,
  `flashnotes_date_fk` int(11) DEFAULT NULL,
  `product_fk` int(11) DEFAULT NULL,
  `school_fk` int(11) DEFAULT NULL,
  `course_fk` int(11) DEFAULT NULL,
  `seller_fk` int(11) DEFAULT NULL,
  `buyer_fk` int(11) DEFAULT NULL,
  `extended_sales_amount` decimal(10,2) DEFAULT NULL,
  `quantity` int(11) DEFAULT NULL,
  `seller_unit_price` decimal(10,2) DEFAULT NULL,
  `transaction_fee` decimal(10,2) DEFAULT NULL,
  `extended_discount_amount` decimal(10,2) DEFAULT NULL,
  `sale_datetime` datetime DEFAULT NULL,
  `payment_method_fk` int(11) DEFAULT NULL,
  `seller_disability_program_fk` int(11) DEFAULT NULL,
  `buyer_disability_program_fk` int(11) DEFAULT NULL,
  `site_fk` int(11) DEFAULT NULL,
  `bundle_purchased_fk` int(11) DEFAULT NULL,
  `affiliate_fk` int(11) DEFAULT NULL,
  KEY `product_sale_product_idx` (`product_fk`),
  KEY `product_sale_seller_idx` (`seller_fk`),
  KEY `product_sale_buyer_idx` (`buyer_fk`),
  KEY `product_sale_date_idx` (`date_fk`),
  KEY `product_sale_flashnotes_date_idx` (`flashnotes_date_fk`),
  KEY `product_sale_school_idx` (`school_fk`),
  KEY `product_sale_payment_method_idx` (`payment_method_fk`),
  KEY `product_sale_seller_disability_program_idx` (`seller_disability_program_fk`),
  KEY `product_sale_buyer_disability_program_idx` (`buyer_disability_program_fk`),
  KEY `product_sale_site_idx` (`site_fk`),
  KEY `product_sale_bundle_purchased_idx` (`bundle_purchased_fk`),
  KEY `product_sale_course_idx` (`course_fk`),
  KEY `product_sale_affiliate_idx` (`affiliate_fk`),
  CONSTRAINT `product_sale_flashnotes_date` FOREIGN KEY (`flashnotes_date_fk`) REFERENCES `date_dim` (`date_key`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8